FLASK_DEBUG=1
DEBUG=True
WTF_CSRF_ENABLED=False
SECRET_KEY="testing"
TESTING=True
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_ECHO = False

# https://github.com/jarus/flask-testing/issues/21#issuecomment-54517959
PRESERVE_CONTEXT_ON_EXCEPTION = False
